FROM python:3.7-alpine

RUN  apk update && apk add --virtual build-deps gcc \ 
	python-dev musl-dev && apk \
    add postgresql-dev

WORKDIR '/app'
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

EXPOSE 3000

ENV APPLICATION_HOST 0.0.0.0

RUN ["python", "manage.py", "db", "migrate"]
CMD ["python", "main.py"]

