version: '3'
services:
  postgres:
    image: 'postgres:latest'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - APPLICATION_POSTGRES_USER=postgres
      - APPLICATION_POSTGRES_HOST=postgres
      - APPLICATION_POSTGRES_DB=postgres
      - APPLICATION_POSTGRES_PW=postgres_password
      - APPLICATION_POSTGRES_PORT=5432
    depends_on:
      - postgres